### ISSUE TITLE
Over engineered

### ISSUE THREAD

**Issue by notsquirr3l** [rciworks/RCi.Tutorials.Csgo.Cheat.External#1]
The complexity of the code would be really off putting to new developers, You might want to consider redoing a lot of this code with less abstraction.

**Comment by martynasapanavicius** [comment]
> The complexity of the code would be really off putting to new developers, You might want to consider redoing a lot of this code with less abstraction.

This is not for absolute beginners. Also I'd say the code is not really too difficult. Including that it is missing proper interprocess memory scraping, thread synchronization and etc. I'm challenging you to fork this repo (or start a fresh code base) and proceed with simplification. I'm pretty sure that would be a great contribution.
