### ISSUE TITLE
Managed Debugging Assistant 'LoaderLock'

### ISSUE THREAD

**Issue by RasyidMF** [rciworks/RCi.Tutorials.Csgo.Cheat.External#2]
Never got this error but for this time. Do you have any solutions to fix this ?
'DLL 'C:\Windows\assembly\GAC\Microsoft.DirectX.Direct3D\1.0.2902.0__31bf3856ad364e35\Microsoft.DirectX.Direct3D.dll' is attempting managed execution inside OS Loader lock. Do not attempt to run managed code inside a DllMain or image initialization function since doing so can cause the application to hang.'

**Comment by MrClue** [comment]
Please tell me how you fixed this problem
